export const FETCHING_COLLATION = 'FETCHING_COLLATION'
export const FETCHING_COLLATION_ERROR = 'FETCHING_COLLATION_ERROR'
export const RECEIVE_COLLATION = 'RECEIVE_COLLATION'
export const RESET_COLLATION = 'RESET_COLLATION'
