export const FETCHING_POEM = 'FETCHING_POEM'
export const FETCHING_POEM_ERROR = 'FETCHING_POEM_ERROR'

export const RECEIVE_POEM = 'RECEIVE_POEM'
export const POEM_NOT_FOUND_ERROR = 'POEM_NOT_FOUND_ERROR'
